name: Deploy Workers

on:
  push:
    branches:
      - master
    paths:
      - apps/before-evening-fe/** # Only triggers on changes in the worker folder
      - apps/before-evening-game-engine/** # Only triggers on changes in the worker folder
      - apps/shared/** # Only triggers on changes in the worker folder

jobs:
  deploy-before-evening-fe-worker:
    runs-on: ubuntu-latest
    name: Deploy before-evening-fe Worker
    steps:
      - uses: actions/checkout@v5
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.4.1
      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
        shell: bash
      - name: Build game engine
        run: pnpm build
        shell: bash
        working-directory: ./apps/before-evening-game-engine
      - name: Build shared module
        run: pnpm build
        shell: bash
        working-directory: ./apps/shared
      - name: Build FE app
        run: pnpm build
        shell: bash
        working-directory: ./apps/before-evening-fe
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: "apps/before-evening-fe"
          command: |
            pages deploy ./build/client --branch=master
